{% set name = "deeppurpose" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kexinhuang12345/DeepPurpose/archive/v{{ version }}.tar.gz
  sha256: 921f820ce7e92c5855d5908a45a6b6365ab340a78220fb7d26f0efbf9b2bc88a

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools >=38.6.0
  run:
    - python >=3.6
    - numpy
    - pandas
    - pytorch
    - pandas-flavor
    - lifelines
    - prettytable
    - scikit-learn
    - tqdm
    - rdkit >=2020.03.6
    - requests
    - python-wget
    - matplotlib
    - scipy

test:
  imports:
    - DeepPurpose

about:
  home: https://github.com/kexinhuang12345/DeepPurpose
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Deep Learning Library for Compound and Protein Modeling DTI, Drug Property, PPI, DDI, Protein Function Prediction
extra:
  recipe-maintainers:
    - kexinhuang12345
    - futianfan
